# -*- coding: utf-8 -*-
"""Iris_ML_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18onDV1Nt0vsXY7IUkpFbamhUJttCCKlM

objective:to load dataset and do basic inspection
"""

import pandas as pd
df=pd.read_csv("Iris.csv")
print("dataset loaded successfully")

df.shape

df.head()

df.info()

df.isnull().sum()

df.duplicated().sum()

"""Dataset Summary

The Iris dataset has information about iris flowers like how long and wide the sepalsre how long and wide the petals are. People often use the Iris dataset to teach computers how to put things into groups. The Iris dataset has three kinds of flowers in it which helps us see how computers can use details to figure out what group something belongs to. We use the Iris dataset to learn about the Iris flowers and how to use machine learning to classify the Iris flowers based on things, like sepal length and petal width of the Iris flowers.



"""

import pandas as pd
df = pd.read_csv("Iris.csv")
df.columns

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])

df.head()

df['Species'].unique()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Species']=le.fit_transform(df['Species'])
df.head()

x=df.drop('Species',axis=1)
y=df['Species']
print("features shape :",x.head())
print("target shape:",y.head())

x=df.drop(['Id','Species'],axis=1)
y=df['Species']
print("features shape :",x.shape)
print("target shape:",y.shape)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(
  x,y,test_size=0.2,random_state=42)
print("x_train:",x_train.shape)
print("x_test:",x_test.shape)
print("y_train:",y_train.shape)
print("y_test:",y_test.shape)

df.corr(numeric_only=True)

"""Data Preprocessing

I checked the dataset before model training. Found no missing values. The Species column was already in a format so I did not need to do any extra encoding.

The dataset was split into training and testing sets with 80% for training and 20%, for testing.

I used the training data to build the models and the testing data to see how well they performed.

The model performance was evaluated using the testing data.
"""

from sklearn.model_selection import train_test_split
X = df.drop('Species', axis=1)
y = df['Species']
X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.20,random_state=42
)
print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(8,6))
sns.heatmap(
    df.corr(),
    annot=True,
   cmap='coolwarm'
)
plt.title('Correlation Heatmap')
plt.show()

"""Observation The correlation heatmap shows how features in the dataset relate, to each other.

Petal Length and Petal Width are strongly connected.

They both go up together.

These two features, Length and Petal Width have a strong positive correlation.

The features Petal Length and Petal Width are related.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)
lr_accuracy = accuracy_score(y_test, y_pred_lr)
print("Logistic Regression Accuracy:", lr_accuracy)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)
knn_accuracy = accuracy_score(y_test, y_pred_knn)
print("KNN Accuracy:", knn_accuracy)

"""The KNN model was. It worked really well. We used the test dataset to see how good it is. The KNN model got a high accuracy score. This means the KNN model is really good, at telling what kind of iris flower something is.


"""

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
from sklearn.metrics import accuracy_score
rf_accuracy = accuracy_score(y_test, y_pred_rf)
print("Random Forest Accuracy:", rf_accuracy)

comparison = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'KNN',
        'Random Forest'
    ],
    'Accuracy': [
        lr_accuracy,
        knn_accuracy,
        rf_accuracy
    ]
})

comparison

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
cm = confusion_matrix(y_test, y_pred_rf)
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix - Random Forest")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""Model Comparison

We looked at three machine learning models that were trained and tested using the Iris dataset.

1.Logistic Regression

2.K-Nearest Neighbors, which is also known as KNN

3.Random Forest

We then compared how accurate each of the three models were. The Iris dataset was used for all three models. All the models did a job with the Iris dataset but the Random Forest model did a really good job. The Random Forest model was very accurate. We compared the accuracy scores of the Logistic Regression model and the K-Nearest Neighbors model, to the Random Forest model. The Random Forest model was the best.

# Confusion Matrix Analysis
I took a look at the best model we have. I made a table called a confusion matrix to see how well it can tell the different iris flowers apart. The table showed that the model got most of the test samples right. There were not samples that the model got wrong. This means the model is really good, at telling the three types of iris flowers. So we can trust this model to do a job of classifying iris flowers.

# **Key Findings**
1.The Iris dataset was really clean. Had no missing values, which made it perfect for machine learning tasks.

2.I found that Petal Length and Petal Width were super important, in telling flower species apart.

3.All three machine learning models did great on the test dataset with high accuracy scores.

4.The Random Forest model performed the overall among the models I tested.
"""